### ISSUE TITLE
error

### ISSUE THREAD

**Issue by OtaconUs** [Urucas/electron-packager-interactive#14]
Electron packager settings:
{ dir: 'C:\\Users\\CTPlate\\Desktop\\Santos\\k',
  name: 'xxxx',
  platform: 'all',
  arch: 'all',
  version: '1.2.2',
  out: 'C:\\Users\\CTPlate\\Desktop\\Santos\\k\\releases',
  'app-bundle-id': '',
  'app-version': '',
  overwrite: true,
  asar: false,
  icon: '',
  app_version: '0.0.1',
  bundle_id: '',
  appname: 'xxxx',
  sourcedir: 'C:\\Users\\CTPlate\\Desktop\\Santos\\k',
  ignore: 'C:\\Users\\CTPlate\\Desktop\\Santos\\k\\releases' }
readline.js:921
            throw err;
            ^

TypeError: Object.assign is not a function
    at Object.createDownloadOpts (C:\Users\CTPlate\AppData\Roaming\npm\node_modules\electron-packager-interactive\node_modules\electron-packager\common.js:187:31)
    at C:\Users\CTPlate\AppData\Roaming\npm\node_modules\electron-packager-interactive\node_modules\electron-packager\index.js:96:32
    at Array.forEach (native)
    at C:\Users\CTPlate\AppData\Roaming\npm\node_modules\electron-packager-interactive\node_modules\electron-packager\index.js:93:15
    at Array.forEach (native)
    at createSeries (C:\Users\CTPlate\AppData\Roaming\npm\node_modules\electron-packager-interactive\node_modules\electron-packager\index.js:92:9)
    at C:\Users\CTPlate\AppData\Roaming\npm\node_modules\electron-packager-interactive\node_modules\electron-packager\index.js:210:12
    at getNameAndVersion (C:\Users\CTPlate\AppData\Roaming\npm\node_modules\electron-packager-interactive\node_modules\electron-packager\index.js:49:34)
    at packager (C:\Users\CTPlate\AppData\Roaming\npm\node_modules\electron-packager-interactive\node_modules\electron-packager\index.js:196:3)
    at run_electron_packager (C:\Users\CTPlate\AppData\Roaming\npm\node_modules\electron-packager-interactive\dist\index.js:46:36)
    at null.completed (C:\Users\CTPlate\AppData\Roaming\npm\node_modules\electron-packager-interactive\dist\index.js:155:5)
    at PromptUI.onCompletion (C:\Users\CTPlate\AppData\Roaming\npm\node_modules\electron-packager-interactive\node_modules\inquirer\lib\ui\prompt.js:56:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (C:\Users\CTPlate\AppData\Roaming\npm\node_modules\electron-packager-interactive\node_modules\rx-lite\rx.lite.js:1826:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\CTPlate\AppData\Roaming\npm\node_modules\electron-packager-interactive\node_modules\rx-lite\rx.lite.js:1763:14)
    at AnonymousObserver.tryCatcher (C:\Users\CTPlate\AppData\Roaming\npm\node_modules\electron-packager-interactive\node_modules\rx-lite\rx.lite.js:537:29)
    at AutoDetachObserverPrototype.completed (C:\Users\CTPlate\AppData\Roaming\npm\node_modules\electron-packager-interactive\node_modules\rx-lite\rx.lite.js:5435:56)

**Comment by vrunoa** [comment]
@OtaconUs as I'm reading the error, I see the error is on **electron-packager**. Let me check into **electron-packager** source to find what is failing.

**Comment by OtaconUs** [comment]
Fixed, only IOJS uninstall and install the latest version of NodeJS.
Solucionado, únicamente desinstale IOJS y instale la ultima versión de NodeJS.

**Comment by vrunoa** [comment]
Thanks for the feedback @OtaconUs
