### ISSUE TITLE
throw errnoException(err, 'spawn');

### ISSUE THREAD

**Issue by JFixby** [Urucas/electron-packager-interactive#36]
```
...
Packaging app for platform linux x64 using electron v1.6.15
Packaging app for platform win32 x64 using electron v1.6.15
internal/child_process.js:366
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:366:11)
    at spawn (child_process.js:551:9)
    at Object.execFile (child_process.js:221:15)
    at Object.exec (child_process.js:152:18)
    at pruneModules (/usr/local/lib/node_modules/electron-packager-interactive/node_modules/electron-packager/prune.js:29:11)
    at Array.<anonymous> (/usr/local/lib/node_modules/electron-packager-interactive/node_modules/electron-packager/common.js:297:9)
    at each (/usr/local/lib/node_modules/electron-packager-interactive/node_modules/run-series/index.js:19:24)
    at CB (/usr/local/lib/node_modules/electron-packager-interactive/node_modules/fs-extra/lib/remove/rimraf.js:57:5)
    at options.unlink.er (/usr/local/lib/node_modules/electron-packager-interactive/node_modules/fs-extra/lib/remove/rimraf.js:107:14)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
```

**Comment by mhjn-varun** [comment]
I have the same error... is there any update on this?
